/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Aprendizaje;
import modelo.Especialidad;
import modelo.Formacion;
import controlador.ControladorAprendizaje;
import controlador.ControladorEspecialidad;
import controlador.ControladorRubro;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author bangho
 */
public class AbmActividades extends javax.swing.JInternalFrame {

    Especialidad especialidad;
    Aprendizaje aprendizaje;
    Formacion formacion;
    JRadioButton jrbCursoSii;
    JRadioButton jrbCursoNoo;
    ButtonGroup gb;

    public AbmActividades() {
        initComponents();

        especialidad = new Especialidad();
        aprendizaje = new Aprendizaje();
        formacion = new Formacion();
        jrbCursoSii = new JRadioButton();
        jrbCursoNoo = new JRadioButton();
        gb = new ButtonGroup();
        //gb.add(jrbCursoSii);
        //gb.add(jrbCursoNoo);
        gb.clearSelection();
        gb.add(jrbCursoSii);
        gb.add(jrbCursoNoo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void botonDesactivado() {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
