/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.abm;

import controlador.ControladorHerramienta;
import controlador.ControladorTipoHerramienta;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import modelo.Herramienta;
import modelo.TipoHerramienta;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author bangho
 */
public class ABMHerramienta extends javax.swing.JInternalFrame {

    Herramienta herramienta;
    ControladorTipoHerramienta cth = new ControladorTipoHerramienta();
    ControladorHerramienta ch=new ControladorHerramienta();
    ArrayList<TipoHerramienta> arrayTHerramienta = new ArrayList<TipoHerramienta>();
    DefaultComboBoxModel<TipoHerramienta> boxModel;

    /*
     public AbmDependencia(String operacion,Dependencia dependencia) {
     // obtengo los parametros y se lo asigno a las propiedades de la clase
     this.operacion = operacion;
     this.dependencia=dependencia;
     //obtengo dependencias
     dependenciasSuperior=(ArrayList<Dependencia>)dc.extraerTodos();
     //genero vector dependecnias para cargar el modelo del combobox
     Dependencia[] d=new Dependencia[dependenciasSuperior.size()];
     for (int i = 0; i < dependenciasSuperior.size(); i++) {     
     d[i]=dependenciasSuperior.get(i);
     }
     */
    public ABMHerramienta() {

        initComponents();

    }

    public ABMHerramienta(Herramienta herramienta) {

        this.herramienta = herramienta;

        arrayTHerramienta = (ArrayList<TipoHerramienta>) cth.extraerTodos();

        TipoHerramienta[] h = new TipoHerramienta[arrayTHerramienta.size()];
        for (int i = 0;i<arrayTHerramienta.size(); i++) {

            h[i] = arrayTHerramienta.get(i);

        }
        boxModel = new DefaultComboBoxModel<TipoHerramienta>(h);
        initComponents();
        jcbTipoHerramienta.setModel(boxModel);
        jcbTipoHerramienta.setSelectedItem(null);
        
        AutoCompleteDecorator.decorate(jcbTipoHerramienta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtfNombreHerramienta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbTipoHerramienta = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtfDescripcionHerramienta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("ABM Herramientas");

        jLabel2.setText("Nombre de Herramienta:");

        jLabel4.setText("Tipo Herramienta:");

        jcbTipoHerramienta.setEditable(true);

        jLabel3.setText("Descripción Herramienta:");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombreHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbTipoHerramienta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfDescripcionHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNombreHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbTipoHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jtfDescripcionHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Boton aceptar ---> Agrega a la BD otra Herramienta.-

        String nombreH = jtfNombreHerramienta.getText();
        Integer tipoH = Integer.parseInt((String) jcbTipoHerramienta.getSelectedItem());
        String descripcionH = jtfDescripcionHerramienta.getText();

        herramienta.setNombreHerramienta(nombreH);
        herramienta.setTipoHerramienta(tipoH);
        //herramienta.setTipoHerramienta(tipoH);
        herramienta.setDescripcion(descripcionH);

        ch.agregar(herramienta);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Boton cancelar
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jcbTipoHerramienta;
    private javax.swing.JTextField jtfDescripcionHerramienta;
    private javax.swing.JTextField jtfNombreHerramienta;
    // End of variables declaration//GEN-END:variables
}
